# Use root/example as user/password credentials
version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - app-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-tier

  server:
    container_name: omni-cim-server
    build: omni-cim-server/
    command: npm start
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - app-tier

  panel:
    container_name: omni-cim-panel
    build: omni-cim-panel/
    # volumes:
    # - '.:/omni-cim-panel/'
    #   - '/omni-cim-panel/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    network_mode: host
    stdin_open: true
    depends_on:
      - server
